package provision

import (
	"context"
	"fmt"

	incuscli "github.com/lxc/incus/v6/client"
	"github.com/gschlager/silo/internal/incus"
)

// systemActivationFile bootstraps the per-user activation file for bash login
// shells. Fedora's /etc/profile sources /etc/profile.d/*.sh, so every bash login
// shell (setup, run, daemons, enter) picks it up.
const systemActivationFile = "/etc/profile.d/silo.sh"

// UserActivationFile is the per-user, user-writable file sourced by every login
// shell. PATH tweaks, env: exports, and tool activations (rv, mise, …) all live
// here so they work for bash and zsh alike and are picked up by daemons and
// non-interactive `silo run` — unlike ~/.zshrc, which is interactive-only.
// Project setup and presets append to it without sudo.
const UserActivationFile = "$HOME/.silo/env.sh"

// setupActivation creates the shell-neutral activation seam for the dev user:
// a user-writable ~/.silo/env.sh (seeded with the ~/.local/bin PATH tweak) plus
// the bootstrap that sources it. bash login shells source it through
// /etc/profile.d/silo.sh; zsh through a guarded line in ~/.zshenv (sourced in
// every zsh mode, including non-interactive daemons).
func setupActivation(ctx context.Context, server incuscli.InstanceServer, container, username, shell string) error {
	rootOpts := incus.ExecOpts{}
	userOpts := incus.ExecOpts{User: 1000, Home: "/home/" + username}
	homeDir := "/home/" + username

	// Per-user activation file (user-writable so setup/presets can append).
	if _, err := incus.Exec(ctx, server, container, userOpts, []string{
		"sh", "-c", "mkdir -p ~/.silo",
	}); err != nil {
		return fmt.Errorf("creating ~/.silo: %w", err)
	}
	seed := `export PATH="$HOME/.local/bin:$PATH"` + "\n"
	if _, err := incus.ExecWithStdin(ctx, server, container, userOpts, []string{
		"tee", homeDir + "/.silo/env.sh",
	}, []byte(seed)); err != nil {
		return fmt.Errorf("seeding activation file: %w", err)
	}

	// bash bootstrap: source the per-user file from /etc/profile.d.
	bootstrap := "# Generated by silo — do not edit.\n" +
		`[ -f "$HOME/.silo/env.sh" ] && . "$HOME/.silo/env.sh"` + "\n"
	if _, err := incus.ExecWithStdin(ctx, server, container, rootOpts, []string{
		"tee", systemActivationFile,
	}, []byte(bootstrap)); err != nil {
		return fmt.Errorf("writing %s: %w", systemActivationFile, err)
	}

	// zsh bootstrap: zsh does not read /etc/profile in every mode, so source the
	// per-user file from ~/.zshenv (sourced in all zsh modes).
	if shell == "zsh" {
		if _, err := incus.Exec(ctx, server, container, userOpts, []string{
			"sh", "-c", `printf '%s\n' '[ -f "$HOME/.silo/env.sh" ] && . "$HOME/.silo/env.sh"' >> ~/.zshenv`,
		}); err != nil {
			return fmt.Errorf("writing ~/.zshenv: %w", err)
		}
	}
	return nil
}

// appendActivation appends content to the per-user activation file as the dev
// user. Used to record env: exports during provisioning.
func appendActivation(ctx context.Context, server incuscli.InstanceServer, container, username, content string) error {
	userOpts := incus.ExecOpts{User: 1000, Home: "/home/" + username}
	if _, err := incus.ExecWithStdin(ctx, server, container, userOpts, []string{
		"tee", "-a", "/home/" + username + "/.silo/env.sh",
	}, []byte(content)); err != nil {
		return fmt.Errorf("appending to activation file: %w", err)
	}
	return nil
}
