package provision

import (
	"fmt"
	"os"
	"os/exec"
	"strings"

	incuscli "github.com/lxc/incus/v6/client"
	"github.com/gschlager/silo/internal/config"
	"github.com/gschlager/silo/internal/incus"
)

// ConfigureGit sets up .gitconfig inside the container for the dev user.
func ConfigureGit(server incuscli.InstanceServer, container, username string, settings map[string]string) error {
	userOpts := incus.UserOpts("/home/"+username, "/home/"+username)

	for key, value := range settings {
		if _, err := incus.Exec(server, container, userOpts, []string{
			"git", "config", "--global", key, value,
		}); err != nil {
			return fmt.Errorf("setting git config %q: %w", key, err)
		}
	}
	return nil
}

// SetupCredentialHelper configures a git credential helper inside the container.
func SetupCredentialHelper(server incuscli.InstanceServer, container, username string, cred *config.CredentialConfig) error {
	if cred == nil {
		return nil
	}

	token, err := resolveCredential(cred)
	if err != nil {
		return fmt.Errorf("resolving git credential: %w", err)
	}

	rootOpts := incus.ExecOpts{}
	userOpts := incus.UserOpts("/home/"+username, "/home/"+username)

	// Create the helper directory.
	if _, err := incus.Exec(server, container, rootOpts, []string{
		"su", "-", username, "-c", "mkdir -p ~/.silo",
	}); err != nil {
		return fmt.Errorf("creating .silo directory: %w", err)
	}

	// Write the credential helper script.
	helperScript := fmt.Sprintf(`#!/bin/sh
# Generated by silo — do not edit
cat <<'CRED'
protocol=https
host=github.com
username=x-access-token
password=%s
CRED
`, token)

	if _, err := incus.Exec(server, container, rootOpts, []string{
		"sh", "-c", fmt.Sprintf(
			`cat > /home/%s/.silo/git-credential-helper << 'SCRIPT'
%sSCRIPT
chmod 700 /home/%s/.silo/git-credential-helper
chown %s:%s /home/%s/.silo/git-credential-helper`,
			username, helperScript, username, username, username, username),
	}); err != nil {
		return fmt.Errorf("writing credential helper: %w", err)
	}

	// Configure git to use the helper.
	if _, err := incus.Exec(server, container, userOpts, []string{
		"git", "config", "--global",
		"credential.https://github.com.helper",
		fmt.Sprintf("/home/%s/.silo/git-credential-helper", username),
	}); err != nil {
		return fmt.Errorf("configuring credential helper: %w", err)
	}

	return nil
}

// resolveCredential resolves a credential from its configured source.
// This runs on the HOST, not inside the container.
func resolveCredential(cred *config.CredentialConfig) (string, error) {
	switch cred.Source {
	case "1password":
		if cred.Ref == "" {
			return "", fmt.Errorf("1password credential requires 'ref' field")
		}
		out, err := exec.Command("op", "read", cred.Ref).Output()
		if err != nil {
			return "", fmt.Errorf("reading from 1Password (%s): %w", cred.Ref, err)
		}
		return strings.TrimSpace(string(out)), nil

	case "token":
		if cred.Value != "" {
			return cred.Value, nil
		}
		if cred.Env != "" {
			val := os.Getenv(cred.Env)
			if val == "" {
				return "", fmt.Errorf("environment variable %q is not set", cred.Env)
			}
			return val, nil
		}
		return "", fmt.Errorf("token credential requires 'value' or 'env' field")

	default:
		return "", fmt.Errorf("unknown credential source: %q", cred.Source)
	}
}
