package provision

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"sort"
	"strings"

	"github.com/gschlager/silo/internal/config"
	"github.com/gschlager/silo/internal/incus"
	incuscli "github.com/lxc/incus/v7/client"
)

// ConfigureGit sets up .gitconfig inside the container for the dev user.
func ConfigureGit(ctx context.Context, server incuscli.InstanceServer, container, username string, settings map[string]string) error {
	userOpts := incus.UserOpts("/home/"+username, "/home/"+username)

	for key, value := range settings {
		if _, err := incus.Exec(ctx, server, container, userOpts, []string{
			"git", "config", "--global", key, value,
		}); err != nil {
			return fmt.Errorf("setting git config %q: %w", key, err)
		}
	}
	return nil
}

// InstallGitHubCredentialHelper configures a git credential helper for github.com
// inside the container. The helper reads $GITHUB_TOKEN from the environment at
// git-invocation time rather than baking a token into the container, so the
// token lives only in the session/setup environment (resolved fresh per session)
// and rotating it needs no reprovision.
func InstallGitHubCredentialHelper(ctx context.Context, server incuscli.InstanceServer, container, username string) error {
	rootOpts := incus.ExecOpts{}
	userOpts := incus.UserOpts("/home/"+username, "/home/"+username)

	// Helper script. The single-quoted outer heredoc writes $GITHUB_TOKEN
	// literally; it is expanded by the shell only when git runs the helper.
	helperScript := `#!/bin/sh
# Generated by silo — do not edit
[ "$1" = get ] || exit 0
cat <<CRED
protocol=https
host=github.com
username=x-access-token
password=$GITHUB_TOKEN
CRED
`

	if _, err := incus.Exec(ctx, server, container, rootOpts, []string{
		"sh", "-c", fmt.Sprintf(
			`mkdir -p /home/%s/.silo
cat > /home/%s/.silo/git-credential-helper << 'SCRIPT'
%sSCRIPT
chmod 700 /home/%s/.silo/git-credential-helper
chown -R %s:%s /home/%s/.silo`,
			username, username, helperScript, username, username, username, username),
	}); err != nil {
		return fmt.Errorf("writing credential helper: %w", err)
	}

	// Configure git to use the helper.
	if _, err := incus.Exec(ctx, server, container, userOpts, []string{
		"git", "config", "--global",
		"credential.https://github.com.helper",
		fmt.Sprintf("/home/%s/.silo/git-credential-helper", username),
	}); err != nil {
		return fmt.Errorf("configuring credential helper: %w", err)
	}

	return nil
}

// ResolveSessionEnv resolves every credential source for a project into
// environment variables: secrets: blocks from the presets the project opted
// into, then the central secrets file, then tool credentials and git.credential
// (each overriding the last). Runs on the host; tokens are returned for passing
// as exec env and are never written to disk. The reserved "github" secret
// populates GITHUB_TOKEN and GH_TOKEN; the git helper consumes the former.
func ResolveSessionEnv(cfg *config.MergedConfig) (map[string]string, error) {
	env := map[string]string{}

	// Preset secrets are the base so a project can override an inherited
	// reference by naming it in its own secrets.yml block.
	if err := resolveSecretsInto(env, cfg.PresetSecrets, "preset secret"); err != nil {
		return nil, err
	}

	secrets, err := config.SecretsForProjects(cfg.ProjectName(), cfg.PathScopedProjectName())
	if err != nil {
		return nil, err
	}
	if err := resolveSecretsInto(env, secrets, "secret"); err != nil {
		return nil, err
	}

	tools, err := ResolveToolEnv(cfg.Tools)
	if err != nil {
		return nil, err
	}
	for k, v := range tools {
		env[k] = v
	}

	if cfg.GitCredential != nil {
		val, err := resolveCredential(cfg.GitCredential)
		if err != nil {
			return nil, fmt.Errorf("resolving git credential: %w", err)
		}
		env["GITHUB_TOKEN"] = val
	}

	return env, nil
}

// ResolveAgentEnv builds the environment an agent is launched with: the active
// mode's env block (from the global config) as the base, with the project-level
// agent env layered on top. Values are literals or op:// references, resolved
// from 1Password on the host at launch time and passed as exec env — never
// written to disk, matching how secrets are handled elsewhere.
func ResolveAgentEnv(agent config.MergedAgentConfig) (map[string]string, error) {
	raw := map[string]string{}
	if mc, ok := agent.Modes[agent.Mode]; ok {
		for k, v := range mc.Env {
			raw[k] = v
		}
	}
	for k, v := range agent.Env {
		raw[k] = v
	}

	resolved := make(map[string]string, len(raw))
	for k, ref := range raw {
		val, err := resolveSecret(ref)
		if err != nil {
			return nil, fmt.Errorf("resolving agent env %q: %w", k, err)
		}
		resolved[k] = val
	}
	return resolved, nil
}

// resolveSecretsInto resolves each reference in secrets and adds it to env under
// its own name, applying the reserved "github" mapping. Names are visited in
// sorted order so a failure reports the same entry every run rather than
// whichever one map iteration reached first. what names the source in errors.
func resolveSecretsInto(env, secrets map[string]string, what string) error {
	names := make([]string, 0, len(secrets))
	for name := range secrets {
		names = append(names, name)
	}
	sort.Strings(names)

	for _, name := range names {
		val, err := resolveSecret(secrets[name])
		if err != nil {
			return fmt.Errorf("resolving %s %q: %w", what, name, err)
		}
		if name == "github" {
			env["GITHUB_TOKEN"] = val
			env["GH_TOKEN"] = val
			continue
		}
		env[name] = val
	}
	return nil
}

// resolveSecret resolves a secrets-file value: a 1Password reference (op://…) is
// read via the op CLI on the host; anything else is treated as a literal.
func resolveSecret(ref string) (string, error) {
	if strings.HasPrefix(ref, "op://") {
		out, err := exec.Command("op", "read", ref).Output()
		if err != nil {
			return "", fmt.Errorf("reading from 1Password (%s): %w", ref, err)
		}
		return strings.TrimSpace(string(out)), nil
	}
	return ref, nil
}

// resolveCredential resolves a credential from its configured source.
// This runs on the HOST, not inside the container.
func resolveCredential(cred *config.CredentialConfig) (string, error) {
	switch cred.Source {
	case "1password":
		if cred.Ref == "" {
			return "", fmt.Errorf("1password credential requires 'ref' field")
		}
		out, err := exec.Command("op", "read", cred.Ref).Output()
		if err != nil {
			return "", fmt.Errorf("reading from 1Password (%s): %w", cred.Ref, err)
		}
		return strings.TrimSpace(string(out)), nil

	case "token":
		if cred.Value != "" {
			return cred.Value, nil
		}
		if cred.Env != "" {
			val := os.Getenv(cred.Env)
			if val == "" {
				return "", fmt.Errorf("environment variable %q is not set", cred.Env)
			}
			return val, nil
		}
		return "", fmt.Errorf("token credential requires 'value' or 'env' field")

	default:
		return "", fmt.Errorf("unknown credential source: %q", cred.Source)
	}
}
