package provision

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"strings"

	incuscli "github.com/lxc/incus/v6/client"
	"github.com/gschlager/silo/internal/config"
	"github.com/gschlager/silo/internal/incus"
)

// ConfigureGit sets up .gitconfig inside the container for the dev user.
func ConfigureGit(ctx context.Context, server incuscli.InstanceServer, container, username string, settings map[string]string) error {
	userOpts := incus.UserOpts("/home/"+username, "/home/"+username)

	for key, value := range settings {
		if _, err := incus.Exec(ctx, server, container, userOpts, []string{
			"git", "config", "--global", key, value,
		}); err != nil {
			return fmt.Errorf("setting git config %q: %w", key, err)
		}
	}
	return nil
}

// InstallGitHubCredentialHelper configures a git credential helper for github.com
// inside the container. The helper reads $GITHUB_TOKEN from the environment at
// git-invocation time rather than baking a token into the container, so the
// token lives only in the session/setup environment (resolved fresh per session)
// and rotating it needs no reprovision.
func InstallGitHubCredentialHelper(ctx context.Context, server incuscli.InstanceServer, container, username string) error {
	rootOpts := incus.ExecOpts{}
	userOpts := incus.UserOpts("/home/"+username, "/home/"+username)

	// Helper script. The single-quoted outer heredoc writes $GITHUB_TOKEN
	// literally; it is expanded by the shell only when git runs the helper.
	helperScript := `#!/bin/sh
# Generated by silo — do not edit
[ "$1" = get ] || exit 0
cat <<CRED
protocol=https
host=github.com
username=x-access-token
password=$GITHUB_TOKEN
CRED
`

	if _, err := incus.Exec(ctx, server, container, rootOpts, []string{
		"sh", "-c", fmt.Sprintf(
			`mkdir -p /home/%s/.silo
cat > /home/%s/.silo/git-credential-helper << 'SCRIPT'
%sSCRIPT
chmod 700 /home/%s/.silo/git-credential-helper
chown -R %s:%s /home/%s/.silo`,
			username, username, helperScript, username, username, username, username),
	}); err != nil {
		return fmt.Errorf("writing credential helper: %w", err)
	}

	// Configure git to use the helper.
	if _, err := incus.Exec(ctx, server, container, userOpts, []string{
		"git", "config", "--global",
		"credential.https://github.com.helper",
		fmt.Sprintf("/home/%s/.silo/git-credential-helper", username),
	}); err != nil {
		return fmt.Errorf("configuring credential helper: %w", err)
	}

	return nil
}

// ResolveSessionEnv resolves every credential source for a project into
// environment variables: the central secrets file (base), then tool credentials
// and git.credential (which override). Runs on the host; tokens are returned for
// passing as exec env and are never written to disk. The reserved "github"
// secret populates GITHUB_TOKEN and GH_TOKEN; the git helper consumes the former.
func ResolveSessionEnv(cfg *config.MergedConfig) (map[string]string, error) {
	env := map[string]string{}

	secrets, err := config.SecretsForProject(cfg.ProjectName())
	if err != nil {
		return nil, err
	}
	for name, ref := range secrets {
		val, err := resolveSecret(ref)
		if err != nil {
			return nil, fmt.Errorf("resolving secret %q: %w", name, err)
		}
		if name == "github" {
			env["GITHUB_TOKEN"] = val
			env["GH_TOKEN"] = val
		} else {
			env[name] = val
		}
	}

	tools, err := ResolveToolEnv(cfg.Tools)
	if err != nil {
		return nil, err
	}
	for k, v := range tools {
		env[k] = v
	}

	if cfg.GitCredential != nil {
		val, err := resolveCredential(cfg.GitCredential)
		if err != nil {
			return nil, fmt.Errorf("resolving git credential: %w", err)
		}
		env["GITHUB_TOKEN"] = val
	}

	return env, nil
}

// resolveSecret resolves a secrets-file value: a 1Password reference (op://…) is
// read via the op CLI on the host; anything else is treated as a literal.
func resolveSecret(ref string) (string, error) {
	if strings.HasPrefix(ref, "op://") {
		out, err := exec.Command("op", "read", ref).Output()
		if err != nil {
			return "", fmt.Errorf("reading from 1Password (%s): %w", ref, err)
		}
		return strings.TrimSpace(string(out)), nil
	}
	return ref, nil
}

// resolveCredential resolves a credential from its configured source.
// This runs on the HOST, not inside the container.
func resolveCredential(cred *config.CredentialConfig) (string, error) {
	switch cred.Source {
	case "1password":
		if cred.Ref == "" {
			return "", fmt.Errorf("1password credential requires 'ref' field")
		}
		out, err := exec.Command("op", "read", cred.Ref).Output()
		if err != nil {
			return "", fmt.Errorf("reading from 1Password (%s): %w", cred.Ref, err)
		}
		return strings.TrimSpace(string(out)), nil

	case "token":
		if cred.Value != "" {
			return cred.Value, nil
		}
		if cred.Env != "" {
			val := os.Getenv(cred.Env)
			if val == "" {
				return "", fmt.Errorf("environment variable %q is not set", cred.Env)
			}
			return val, nil
		}
		return "", fmt.Errorf("token credential requires 'value' or 'env' field")

	default:
		return "", fmt.Errorf("unknown credential source: %q", cred.Source)
	}
}
